name: "Ring" # name of the machine
machine_category: "unknown" # category of the machine
machine_type: "unknown" # type of the machine
machine_model: "unknown" # model of the machine
description: "" # description of the machine
root:
  !!FolderNode
  name: "Ring"
  description: ""
  children:
    - !!NumericalVariableNode
      name: "out"
      description: ""
      measure_unit: "NoneMeasureUnits.NONE"
      value: -1
    - !!NumericalVariableNode
      name: "received"
      description: ""
      measure_unit: "NoneMeasureUnits.NONE"
      value: 0
    - !!BooleanVariableNode
      name: "work"
      description: ""
      value: False
    - !!CompositeMethodNode
      name: "ring"
      description: ""
      parameters:
        - !!NumericalVariableNode
          name: "in"
          description: ""
          value: 0
      returns:
        - !!NumericalVariableNode
          name: "out"
          description: ""
          value: 0
      cfg:
        - !!WriteVariableNode
          variable: "Ring/received"
          value: "$in"
        - !!WriteVariableNode
          variable: "Ring/work"
          value: True
        - !!WaitConditionNode
          variable: "Ring/out"
          operator: ">="
          rhs: 0
        - !!ReadVariableNode
          variable: "Ring/out"
          store_as: "out"
        - !!WriteVariableNode
          variable: "Ring/out"
          value: -1
        - !!WaitConditionNode
          variable: "Ring/out"
          operator: "=="
          rhs: -1
        

